routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

$timezone = 'ASIA/KOLKATA';
$date = new DateTime('now', new DateTimeZone($timezone));
$localtime = $date->format('Y m d h:i:s a');

Route::get('/', 'WelcomeController@index')->name('blog.home');
Route::get('/blog/category/{category}', 'WelcomeController@category')->name('blog.category');
Route::get('/blog/tag/{tag}', 'WelcomeController@tag')->name('blog.tag');
Route::get('/blog/{post}', 'WelcomeController@show')->name('blog.show');

Auth::routes();


/**
 * Resourceful Routes:
 *
 * Most of the time Controllers have these 7 operations :
 * index
 * show
 * create
 * update
 * store
 * edit
 * destroy
 *
 * then we have to write the routes for each operation.
 * so laravel came up with a concept known as Resourceful Routes.
 * Route::resource('user', 'UserController');
 * 1st argument is initial word of the URI.
 * suppose for categories we want to make resourceful routes.
 * so every URI of categories will be like this:
 * /categories/create
 * /categories
 * /categories/{category}
 * /categories/{category}/edit
 * so we will write like this : Route::resource('categories', 'CategoriesController');
 *
 * And the routes would be named as Initial word of the URI.method_name
 * E.g. categories.index
 * categories.show,etc.
 * 2nd argument is the Controller which we want to use.
 *
 *
 * And we have to manually write these 7 methods and we have to manually do Route model binding in Controllers which takes time.
 * to solve this problem we can hit a command:
 * php artisan make:controller --model=model_name
 *
 * By doing this we will get controller with these 7 methods associated in it with Route Model Binding.
 *
 */
/**
 * We have to apply auth middleware to all the routes so instead of assigning middleware to all routes we can create route groups where we can apply middleware to that group.
 * Route::middleware([middlewares])->group(function(){
 *      all the routes
 * })
 */
Route::middleware(['auth'])->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('categories', 'CategoriesController');
    Route::resource('posts', 'PostsController');
    Route::resource('tags', 'TagsController');
    Route::delete('/trash/{post}', 'PostsController@trash')->name('posts.trash');
    Route::get('trashed', 'PostsController@trashed')->name('posts.trashed');
    Route::put('/restore/{id}', 'PostsController@restore')->name('posts.restore');
});
Route::middleware(['auth', 'admin'])->group(function () {
    Route::get('/users', 'UsersController@index')->name('users.index');
    Route::put('/users/{user}/make-admin', 'UsersController@makeAdmin')->name('users.make-admin');
});

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    //
    protected $fillable = ['name'];
    public function posts()
    {
        return $this->belongsToMany(Post::class)->withTimestamps();
    }
}

app/Http/Controllers/TagsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateTagRequest;
use App\Http\Requests\UpdateTagRequest;
use App\Tag;
use Illuminate\Http\Request;

class TagsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $tags = Tag::all();
        return view('tags.index')->withTags($tags);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('tags.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateTagRequest $request)
    {
        //
        Tag::create([
            'name' => $request->name
        ]);
        session()->flash('success', 'Tag Created Successfully');
        return redirect(route('tags.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function show(Tag $tag)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function edit(Tag $tag)
    {
        //
        return view('tags.edit')->withTag($tag);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateTagRequest $request, Tag $tag)
    {
        //
        $tag->update([
            'name' => $request->name
        ]);
        session()->flash('success', 'Tag Updated Successfully');
        return redirect(route('tags.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tag $tag)
    {
        //
        if ($tag->posts->count() > 0) {
            session()->flash('error', 'Tag cannot be Deleted as it is associated with some post!');
            return redirect()->back();
        }
        $tag->delete();
        session()->flash('success', 'Tag Deleted Successfully');
        return redirect(route('tags.index'));
    }
}

resources/views/tags/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="card">
        <div class="card-header">Add Tag</div>

        <div class="card-body">
            <form action="{{ route('tags.store') }}" method="POST">
                @csrf
                <div class="form-group">
                    <label for="name">Name</label>
                <input type="text" name="name" id="name" class="form-control @error('name') is-invalid @enderror" value="{{ old('name') }}">
                @error('name')
                    <p class="text-danger">{{ $message }}</p>
                @enderror
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-success">Add Tag</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/tags/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="card">
        <div class="card-header">Update Tag</div>
        <div class="card-body">
            <form action="{{ route('tags.update',$tag->id) }}" method="POST">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="name">Name</label>
                <input type="text" name="name" id="name" class="form-control @error('name') is-invalid @enderror" value="{{ old('name') ?? $tag->name }}">
                @error('name')
                    <p class="text-danger">{{ $message }}</p>
                @enderror
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-success">Update Tag</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/tags/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="d-flex justify-content-end mb-3">
    <a href="{{ route('tags.create') }}" class="btn btn-primary">Add Tags</a>
    </div>
<div class="card">
    <div class="card-header">Tags</div>

    <div class="card-body">
        <table class="table table-bordered">
            <thead>
                <th>Name</th>
                <th>Posts Count</th>
                <th>Actions</th>
            </thead>
            <tbody>
                @foreach ($tags as $tag)
                    <tr>
                        <td>{{ $tag->name }}</td>
                        <td>
                            {{ $tag->posts->count() }}
                        </td>
                        <td>
                        <a href="{{ route('tags.edit',$tag->id) }}" class="btn btn-primary btn-sm">Edit</a>
                            <a href="" class="btn btn-danger btn-sm"  data-toggle="modal" data-target="#deleteModal" onclick="displayModalForm({{ $tag }})">Delete</a>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
    <!-- DELETE MODAL -->

  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form action="" method="POST" id="deleteForm">
            @csrf
            @method('DELETE')
            <div class="modal-body">
              Are you sure you want to delete Tag?
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-danger">Delete Tag</button>
            </div>
        </form>
      </div>
    </div>
  </div>

@endsection
@section('page-level-scripts')
  <script>
      function displayModalForm(tag)
      {
          let url = `/tags/` + tag.id;
          $('#deleteForm').attr('action',url);
      }
  </script>
@endsection