routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

$timezone = 'ASIA/KOLKATA';
$date = new DateTime('now', new DateTimeZone($timezone));
$localtime = $date->format('Y m d h:i:s a');

Route::get('/', 'WelcomeController@index')->name('blog.home');
Route::get('/blog/category/{category}', 'WelcomeController@category')->name('blog.category');
Route::get('/blog/tag/{tag}', 'WelcomeController@tag')->name('blog.tag');
Route::get('/blog/{post}', 'WelcomeController@show')->name('blog.show');

Auth::routes();


/**
 * Resourceful Routes:
 *
 * Most of the time Controllers have these 7 operations :
 * index
 * show
 * create
 * update
 * store
 * edit
 * destroy
 *
 * then we have to write the routes for each operation.
 * so laravel came up with a concept known as Resourceful Routes.
 * Route::resource('user', 'UserController');
 * 1st argument is initial word of the URI.
 * suppose for categories we want to make resourceful routes.
 * so every URI of categories will be like this:
 * /categories/create
 * /categories
 * /categories/{category}
 * /categories/{category}/edit
 * so we will write like this : Route::resource('categories', 'CategoriesController');
 *
 * And the routes would be named as Initial word of the URI.method_name
 * E.g. categories.index
 * categories.show,etc.
 * 2nd argument is the Controller which we want to use.
 *
 *
 * And we have to manually write these 7 methods and we have to manually do Route model binding in Controllers which takes time.
 * to solve this problem we can hit a command:
 * php artisan make:controller --model=model_name
 *
 * By doing this we will get controller with these 7 methods associated in it with Route Model Binding.
 *
 */
/**
 * We have to apply auth middleware to all the routes so instead of assigning middleware to all routes we can create route groups where we can apply middleware to that group.
 * Route::middleware([middlewares])->group(function(){
 *      all the routes
 * })
 */
Route::middleware(['auth'])->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('categories', 'CategoriesController');
    Route::resource('posts', 'PostsController');
    Route::resource('tags', 'TagsController');
    Route::delete('/trash/{post}', 'PostsController@trash')->name('posts.trash');
    Route::get('trashed', 'PostsController@trashed')->name('posts.trashed');
    Route::put('/restore/{id}', 'PostsController@restore')->name('posts.restore');
});
Route::middleware(['auth', 'admin'])->group(function () {
    Route::get('/users', 'UsersController@index')->name('users.index');
    Route::put('/users/{user}/make-admin', 'UsersController@makeAdmin')->name('users.make-admin');
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Storage;

class Post extends Model
{
    //
    use SoftDeletes; //softDeletes is a trait which gives us methods to maintain soft deletion functionality.
    protected $fillable = [
        'title',
        'excerpt',
        'body',
        'image',
        'published_at',
        'category_id',
        'user_id'
    ];

    protected $dates = ['published_at'];
    // When we retrieve published_at from database we will get string but we want in date format that means Carbon is a class which is used for storing date.
    // in $dates the columns we specify here
    // when we retrieve that columns we'll get an instance of any date object.
    /**
     * Helper Functions
     */
    public function deleteImage()
    {
        // Storage is a facade which contains the method delete
        // it accepts argument as filename to be deleted.
        Storage::delete($this->image);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }
    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }
    public function hasTag($tag_id)
    {
        return in_array($tag_id, $this->tags->pluck('id')->toArray());
    }
    public function author()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    /**
     * Query Scopes
     * Refer notes.txt.
     */
    public function scopeSearch($query)
    {
        $search = request('search');
        if ($search) {
            return $query->where('title', 'like', "%$search%");
        }
        return $query;
    }

    public function scopePublished($query)
    {
        return $query->where('published_at', '<=', now())->latest('published_at');
    }
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Http\Requests\Posts\CreatePostRequest;
use App\Http\Requests\Posts\UpdatePostRequest;
use App\Post;
use App\Tag;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class PostsController extends Controller
{
    public function __construct()
    {
        // Here we will call the middlewares.
        $this->middleware(['verifyCategoriesCount'])->only('create', 'store');
        $this->middleware(['validateAuthor'])->only('edit', 'update', 'destroy', 'trash', 'restore');
        // only means middleware will only be applied to those methods.
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        if (!auth()->user()->isAdmin()) {
            // isAdmin will check whether user is admin or not.
            // auth()->id() returns id of the user currently logged in.
            $posts = Post::withoutTrashed()->where('user_id', auth()->id())->paginate(10);
        } else {

            $posts = Post::paginate(10);
        }
        return view('posts.index', compact(['posts']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $categories = Category::all();
        $tags = Tag::all();
        return view('posts.create')
            ->withCategories($categories)
            ->withTags($tags);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreatePostRequest $request)
    {
        //
        /**
         * When we submit the form we get all the files in the files object.
         * we can  access all the files by using file method of request object.
         * $request->file('name')
         * Refer address-book-master for internal details on filesystem of php.
         * store method is used to store the file.
         * store method accept an argument known as path.
         * path stands for where to store the file.
         * $request->file('image')->('posts')
         *
         *
         *
         * NOTE: when we hit store method it goes to filesystems.php in config folder and retrieves the path that where to store the files.
         * By default it stores into storage/app which is a secured path that means we can't view or access the files from this path.
         * so we have to override the path.we can do it in two ways:
         * 1 . directly change the path in filesystems.php
         * 2 . in the .env file define constant named as FILESYSTEM_DRIVER bcoz filesystems.php first checks that only.
         * write FILESYSTEM_DRIVER = public in .env file.
         * in the filesystems.php it is configured that for public we have to store the file in storage/app/public folder.
         * But still now also we can't access that bcoz we can access files(assets) from public folder only. so we will run a command : php artisan storage:link which creates a symbolic link in public folder.
         * That means it copies whole files of storage/app/public and paste it into public/storage.
         * From there we can access all the assets.
         *
         */
        $image = $request->file('image')->store('posts');
        $post = Post::create([
            'title' => $request->title,
            'excerpt' => $request->excerpt,
            'category_id' => $request->category_id,
            'body' => $request->body,
            'image' => $image,
            'user_id' => auth()->id(),
            'published_at' => $request->published_at
        ]);

        // dd($request->tags);

        $post->tags()->attach($request->tags);
        session()->flash('success', 'Post Created Successfully');
        return redirect(route('posts.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        //
        $categories = Category::all();
        $tags = Tag::all();
        return view('posts.edit', compact(['categories', 'tags', 'post']));
        // Here variable name would be post
        // if we write withArticle then variablename would be article
        // it is achieving this functionality with the help of magic method
        // where it fetches text after 'with' and makes the variablename accordingly.

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(UpdatePostRequest $request, Post $post)
    {
        //Here there are possibilities that image can be changed or it remains same.
        // if no image is chosen then we won't do anything as old image will be there in database.
        // only is the method which takes array and returns only those elements which are there in array as well as in request.
        $data = $request->only(['title', 'excerpt', 'body', 'published_at', 'category_id']);
        if ($request->hasFile('image')) {
            // We will come here if any image is chosen
            // we have to store the new image
            $imageName = $request->image->store('posts'); //store returns name of the file.
            // delete the old image
            $post->deleteImage();
            // change the filename in database
            $data['image'] = $imageName;
        }
        $post->tags()->sync($request->tags);
        $post->update($data);
        session()->flash('success', 'Post Updated successfully');
        return redirect(route('posts.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //Permanently deletes the post.
        // we can't do Route Model Binding here bcoz it works only for those records where deleted_at == NULL.
        // so we have to manually fetch the record.
        // forceDelete is a method which is used to permanently delete the record.
        $post = Post::onlyTrashed()->findOrFail($id);
        $post->deleteImage();
        $post->forceDelete();
        session()->flash('success', 'Post Deleted successfully');
        return redirect()->back();
    }
    public function trash(Post $post)
    {
        // Soft Deletes(Trashes) the Post.

        $post->delete();
        session()->flash('success', 'Post trashed successfully');
        return redirect(route('posts.index'));
    }
    public function trashed()
    {
        //Displays Trashed Posts.

        // $trashed = DB::table('posts')->whereNotNull('deleted_at');
        $trashed = Post::onlyTrashed()->paginate(10); //onlyTrashed is a method of softDeletes Trait.
        // return view('posts.trashed',['posts'=>$trashed]);
        return view('posts.trashed')->with('posts', $trashed); //same as above
    }
    public function restore($id)
    {
        // restores the Post.
        // restore is a method in softDelete Trait.
        $post = Post::onlyTrashed()->findOrFail($id);
        $post->restore();
        session()->flash('success', 'Post Restored successfully');
        return redirect(route('posts.index'));
    }
}

resources/views/posts/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="card">
        <div class="card-header">Add Post</div>
        <div class="card-body">
            <form action="{{ route('posts.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="form-group">
                    <label for="name">Title</label>
                <input type="text" name="title" id="title" class="form-control @error('title') is-invalid @enderror" value="{{ old('title') }}">
                @error('title')
                    <p class="text-danger">{{ $message }}</p>
                @enderror
                </div>

                <div class="form-group">
                    <label for="excerpt">Excerpt</label>
                    <textarea name="excerpt" id="excerpt" rows="4" class="form-control @error('excerpt') is-invalid @enderror">{{ old('excerpt') }}</textarea>
                @error('excerpt')
                    <p class="text-danger">{{ $message }}</p>
                @enderror
                </div>

                <div class="form-group">
                    <label for="name">Body</label>
                    <input id="body" type="hidden" value="{{ old('body') }}" name="body">
                    <trix-editor input="body"></trix-editor>
                @error('body')
                    <p class="text-danger">{{ $message }}</p>
                @enderror
                </div>

                <div class="form-group">
                    <label for="category_id">Category</label>
                    <select name="category_id" id="" class="form-control categories">
                        @foreach ($categories as $category)
                            <option value="{{ $category->id }}">{{$category->name}}</option>
                        @endforeach
                    </select>
                    @error('category_id')
                    <p class="text-danger">{{ $message }}</p>
                @enderror
                </div>

                <div class="form-group">
                    <label for="tags">Tags</label>
                    <select name="tags[]" id="" class="form-control tags" multiple>
                        @foreach ($tags as $tag)
                            <option value="{{ $tag->id }}
                                {{ old('tags') ? (in_array($tag->id,old('tags')) ? 'selected' : '') : '' }}
                                ">{{$tag->name}}</option>
                        @endforeach
                    </select>
                    @error('tags')
                    <p class="text-danger">{{ $message }}</p>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="published_at">Published At</label>
                <input type="text" name="published_at" id="published_at" class="form-control" value="{{ old('published_at') }}">
                @error('published_at')
                <p class="text-danger">{{ $message }}</p>
                @enderror
                </div>

                <div class="form-group">
                    <label for="image">Image</label>
                <input class="form-control  @error('image') is-invalid @enderror" type="file" name="image" value="{{ old('image') }}">
                @error('image')
                <p class="text-danger">{{ $message }}</p>
                @enderror
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-success">Submit</button>
                </div>
            </form>
        </div>
    </div>
@endsection
@section('page-level-styles')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.3/trix.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
@endsection
@section('page-level-scripts')
<script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.3/trix.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.8/js/select2.min.js" defer></script>

    <script>
        flatpickr('#published_at',{
            enableTime: true
        });
        $(document).ready(function() {
            $('.categories').select2();
            $('.tags').select2();
    });
    </script>
@endsection

resources/views/posts/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="card">
        <div class="card-header">Add Category</div>

        <div class="card-body">
            <form action="{{ route('posts.update',$post->id) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="name">Title</label>
                <input type="text" name="title" id="title" class="form-control @error('title') is-invalid @enderror" value="{{ old('title',$post->title) }}">
                @error('title')
                    <p class="text-danger">{{ $message }}</p>
                @enderror
                </div>

                <div class="form-group">
                    <label for="excerpt">Excerpt</label>
                    <textarea name="excerpt" id="excerpt" rows="4" class="form-control @error('excerpt') is-invalid @enderror">{{ old('excerpt',$post->excerpt) }}</textarea>
                @error('excerpt')
                    <p class="text-danger">{{ $message }}</p>
                @enderror
                </div>

                <div class="form-group">
                    <label for="name">Body</label>
                    <input id="body" type="hidden" value="{{ old('body', $post->body) }}" name="body">
                    <trix-editor input="body"></trix-editor>
                @error('body')
                    <p class="text-danger">{{ $message }}</p>
                @enderror
                </div>


                <div class="form-group">
                    <label for="category_id">Category</label>
                    <select name="category_id" id="" class="form-control categories">
                        @foreach ($categories as $category)
                            @if ($post->category->name == $category->name)
                            <option value="{{ $category->id }}" selected>{{$category->name}}</option>
                            @else
                            <option value="{{ $category->id }}">{{$category->name}}</option>
                            @endif
                        @endforeach
                    </select>
                </div>

                <div class="form-group">
                    <label for="tags">Tags</label>
                    <select name="tags[]" id="" class="form-control tags" multiple>
                        @foreach ($tags as $tag)
                            <option value="{{ $tag->id }}"
                                {{ old('tags') ?  (in_array($tag->id,old('tags')) ? 'selected' : '') : ($post->hasTag($tag->id) ? 'selected' : '') }}
                            >{{$tag->name}}</option>
                        @endforeach
                    </select>
                </div>


                <div class="form-group">
                    <label for="published_at">Published At</label>
                <input type="text" name="published_at" id="published_at" class="form-control" value="{{ old('published_at',$post->published_at)  }}">
                </div>
                <div class="form-group">
                    <img src="{{ asset('storage/' . $post->image) }}" alt="" width="100%">
                </div>

                <div class="form-group">
                    <label for="image">Image</label>
                <input class="form-control  @error('image') is-invalid @enderror" type="file" name="image">
                @error('image')
                <p class="text-danger">{{ $message }}</p>
                @enderror
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-success">Submit</button>
                </div>
            </form>
        </div>
    </div>
@endsection
@section('page-level-styles')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.3/trix.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
@endsection
@section('page-level-scripts')
<script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.3/trix.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.8/js/select2.min.js" defer></script>

    <script>
        flatpickr('#published_at',{
            enableTime: true
        });
    </script>
    <script>
        $(document).ready(function() {
            $('.categories').select2();
            $('.tags').select2();
        });
    </script>
@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="d-flex justify-content-end mb-3">
    <a href="{{ route('posts.create') }}" class="btn btn-primary">Add Post</a>
    </div>
<div class="card">
    <div class="card-header">Posts</div>

    <div class="card-body">
        @if ($posts->count() > 0)
        <table class="table table-bordered">
            <thead>
                <th>Image</th>
                <th>Title</th>
                <th>Excerpt</th>
                <th>Author</th>
                <th>Category</th>
                <th>Actions</th>
            </thead>
            <tbody>
                @foreach ($posts as $post)
                    <tr>
                        <td>
                            <img src="{{ asset('storage/' . $post->image) }}" alt="" width="120px">
                        </td>
                        <td>
                            {{ $post->title }}
                        </td>
                        <td>
                            {{ $post->excerpt }}
                        </td>
                        <td>
                            {{ $post->author->name }}
                        </td>
                        <td>
                            {{ $post->category->name }}
                        </td>
                        <td>
                            <a href="{{ route('posts.edit',$post->id) }}" class="btn btn-primary btn-sm">Edit</a>
                            <a href="" class="btn btn-danger btn-sm"  data-toggle="modal" data-target="#deleteModal" onclick="displayModalForm({{ $post }})">Trash</a>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
        @else
            <h3>Nothing to show</h3>
        @endif
    </div>
    <div class="card-footer">
        {{ $posts->links() }}
    </div>
</div>
    <!-- DELETE MODAL -->

  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form action="" method="POST" id="deleteForm">
            @csrf
            @method('DELETE')
            <div class="modal-body">
              Are you sure you want to trash Post?
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-danger">Trash Post</button>
            </div>
        </form>
      </div>
    </div>
  </div>

@endsection
@section('page-level-scripts')
  <script>
      function displayModalForm(post)
      {
          let url = `/trash/` + post.id;
          $('#deleteForm').attr('action',url);
      }
  </script>
@endsection

resources/views/posts/trashed.blade.php
@extends('layouts.app')

@section('content')
<div class="card">
    <div class="card-header">Posts</div>

    <div class="card-body">
        @if($posts->count())
        <table class="table table-bordered">
            <thead>
                <th>Image</th>
                <th>Title</th>
                <th>Excerpt</th>
                <th>Author</th>
                <th>Category</th>
                <th>Actions</th>
            </thead>
            <tbody>
                @foreach ($posts as $post)
                    <tr>
                        <td>
                            <img src="{{ asset('storage/' . $post->image) }}" alt="" width="120px">
                        </td>
                        <td>
                            {{ $post->title }}
                        </td>
                        <td>
                            {{ $post->excerpt }}
                        </td>
                        <td>
                            {{ $post->author->name }}
                        </td>
                        <td>
                            {{ $post->category->name }}
                        </td>
                        <td>
                        <form action="{{ route('posts.restore',$post->id) }}" method="POST">
                            @csrf
                            @method('PUT')
                            <button type="submit" class="btn btn-primary btn-sm">Restore</button>
                        </form>
                            <a href="" class="btn btn-danger btn-sm"  data-toggle="modal" data-target="#deleteModal" onclick="displayModalForm({{ $post }})">Delete</a>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
        @else
            <h3>No trashed Posts</h3>
        @endif
    </div>
    <div class="card-footer">
        {{ $posts->links() }}
    </div>
</div>
    <!-- DELETE MODAL -->

  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form action="" method="POST" id="deleteForm">
            @csrf
            @method('DELETE')
            <div class="modal-body">
              Are you sure you want to delete Post?
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-danger">Delete Post</button>
            </div>
        </form>
      </div>
    </div>
  </div>

@endsection
@section('page-level-scripts')
  <script>
      function displayModalForm(post)
      {
          let url = `/posts/` + post.id;
          $('#deleteForm').attr('action',url);
      }
  </script>
@endsection